version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent trois serveurs todo, trois clients, et un superviseur qui observe les tâches
    c1:
      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret03-c1
      image: arret03-client
      tty: true
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'
      build:
          context: .
          dockerfile: Dockerfile.client

    c2:
      container_name: arret03-c2
      image: arret03-client
      tty: true
      environment:
        - MONSERVEUR='s2'
        - MONNOM='c2'
      build:
          context: .
          dockerfile: Dockerfile.client

    c3:
      container_name: arret03-c3
      image: arret03-client
      tty: true
      environment:
        - MONSERVEUR='s3'
        - MONNOM='c3'
      build:
          context: .
          dockerfile: Dockerfile.client

      
    s1:
      # Premier serveur - Traite les demandes todo
      container_name: arret03-s1
      image: arret03-serveur
      tty: true
      volumes:
        - "./tmp_todo1:/todo"
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'
      build:
          context: .
          dockerfile: Dockerfile.serveur

    s2:
      container_name: arret03-s2
      image: arret03-serveur
      tty: true
      volumes:
        - "./tmp_todo2:/todo"
      environment:
        - MONSERVEUR='s2'
        - MONNOM='c2'
      build:
          context: .
          dockerfile: Dockerfile.serveur

    s3:
      container_name: arret03-s3
      image: arret03-serveur
      tty: true
      volumes:
        - "./tmp_todo3:/todo"
      environment:
        - MONSERVEUR='s3'
        - MONNOM='c3'
      build:
          context: .
          dockerfile: Dockerfile.serveur

    gestionnaire:
      container_name: arret03-gestionnaire
      image: arret03-gestionnaire
      tty: true
      environment:
        - MONSERVEUR='s1,s2,s3'
        - MONNOM='c1,c2,c3'
      build:
          context: .
          dockerfile: Dockerfile.gestionnaire

# Réseau par défaut
networks:
  arret03-todo-net:
